# Generated by Django 4.2.9 on 2024-01-10 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('customer_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('quantity', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('price', models.IntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='invoice_API.invoice')),
            ],
        ),
    ]
