# Generated by Django 4.2.9 on 2024-01-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_API', '0002_alter_invoice_date_alter_invoice_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
