# Generated by Django 4.2.9 on 2024-01-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_API', '0003_alter_invoicedetails_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetails',
            name='price',
        ),
    ]
